### ISSUE TITLE
I can not transfer to the Bittrex wallet.

### ISSUE THREAD

**Issue by tipo7026** [theQRL/qrl-wallet#256] opened 2018-08-03 10:53 UTC
I can not transfer to the Bittrex wallet. Constantly lit the inscription "JAST A MOMENT" and nothing happens. What could be the problem?
![qrl](https://user-images.githubusercontent.com/42063987/43639202-1ca9bdea-9724-11e8-9aa6-eab4c2475d2d.jpg)

**Comment by jplomas** [comment] 2018-08-03 10:59
This is a duplicate of #252

Bittrex are currently using ERC20 addresses which are on the Ethereum blockchain.

You cannot send QRL from a Q-address to an Ethereum 0x-address.

**Closed by jplomas** 2018-08-03 10:59 UTC

**Comment by tipo7026** [comment] 2018-08-03 11:31
And how, then, to bring QRL to the stock exchange?

**Comment by noremac2007** [comment] 2018-08-03 12:31
You can't until some exchange implements new code and accepts the new addresses

**Comment by tipo7026** [comment] 2018-08-03 12:41
Why such a coin?

**Comment by tipo7026** [comment] 2018-08-03 12:41
Why such a coin is needed?

**Comment by tipo7026** [comment] 2018-08-03 12:42
What is the meaning of this coin?

**Comment by jplomas** [comment] 2018-08-03 14:12
The case for a Quantum Resistant Ledger is eloquently made in our Whitepaper: 
https://github.com/theQRL/Whitepaper/blob/master/QRL_whitepaper.pdf
