### ISSUE TITLE
Transfer to stock exchange ERC20 

### ISSUE THREAD

**Issue by miass777** [theQRL/qrl-wallet#267] opened 2018-08-23 06:36 UTC
How can I transfer to Stock Exchange (ERC20 0x deposit address)?
From QRL ERC20 to ERC20 0x deposit address.

**Comment by jplomas** [comment] 2018-08-23 09:01
Dupe of #256 

Please see Discord FAQ

**Closed by jplomas** 2018-08-23 09:01 UTC
Labels: Type: Duplicate
